name: release and deploy

on:
  push:
    branches:
      - main

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Maven setup
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
              "id": "magnolia.enterprise.group",
              "username": "${{secrets.MGNL_NEXUS_USER}}",
              "password": "${{secrets.MGNL_NEXUS_PASS}}"
            }]
      - name: Maven verify
        run: mvn verify --batch-mode
      # Install xmllint
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libxml2-utils
      # Set git user name and email
      - name: Set up Git
        run: |
          chmod +x ci/setup-git.sh
          ci/setup-git.sh
      # Release, set correct versions and create tag
      - name: Release (versioning/tag)
        run: |
          chmod +x ci/mvn-release.sh
          ci/mvn-release.sh

  deploy-release:

    needs: release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'main'
      - name: Maven setup
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
              "id": "magnolia.enterprise.group",
              "username": "${{secrets.MGNL_NEXUS_USER}}",
              "password": "${{secrets.MGNL_NEXUS_PASS}}"
            }]
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Release Maven package
        run: mvn deploy -Pdeploy
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USER }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
